spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5433/storedb
    username: fara
    password: password
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15 minutes
    refreshTokenExpiration: 604800 # 7 days
stripe:
  secretKey: ${STRIPE_SECRET_KEY}